### ISSUE TITLE
Version 0.2.0 not released to pypi

### ISSUE THREAD

**Issue by hellocoldworld** [faust-streaming/mode#12]
Current project version is 0.2.0, but the latest pypi release is 0.1.0. 

Releasing to pypi would be great as it introduces py3.10 support.

**Comment by lqhuang** [comment]
Sure, @taybin, I can help if necessary. Or we could introduce an automated dist release bot?

**Comment by lqhuang** [comment]
@hellocoldworld Sorry, no one responses yet. If you are using py3.10, you could try my fork [`mode-ng`](https://github.com/lqhuang/mode-ng)

**Comment by hellocoldworld** [comment]
@lqhuang problem is that faust-streaming still depends in mode-streaming 0.1.0 ... are you planning on forking faust-ng too?

**Comment by lqhuang** [comment]
@hellocoldworld Oh, sorry, no plan for now. `faust-streaming` is still in active developing currently.

**Comment by wbarnha** [comment]
It's released now 😄
